version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${USER_POSTGRES}
      POSTGRES_PASSWORD: ${PASSWORD_POSTGRES}
    volumes:
      - ${PROJECT_PATH}\postgres\data:/var/lib/postgresql/data
    networks:
      - my-network
    env_file:
      - .env

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${PROJECT_PATH}:/app
      - ${PROJECT_PATH}\gradle\caches:/root/.gradle
      - ${PROJECT_PATH}\ssh\:/root/.ssh
    networks:
      - my-network
    depends_on:
      - postgres
    env_file:
      - .env


networks:
  my-network:

